/*
 * Copyright 2015
 *  http://wazza.co.ke
 * 8:21:59 PM  : Jul 22, 2015
 */
package vertigo;

import com.drew.imaging.ImageMetadataReader;
import com.drew.imaging.ImageProcessingException;
import com.drew.metadata.Directory;
import com.drew.metadata.Metadata;
import com.drew.metadata.Tag;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author kelli
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSplitter = new javax.swing.JSplitPane();
        pnSource = new ImagePanel();
        pnTarget = new ImagePanel();
        pnToolbar = new javax.swing.JPanel();
        btnSelectImg = new javax.swing.JButton();
        lbSelectedFile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ImgEvaluator");
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setLocationByPlatform(true);
        setName("mainFrame"); // NOI18N
        setResizable(false);

        pnSplitter.setResizeWeight(0.5);
        pnSplitter.setName("pnSplitter"); // NOI18N
        pnSplitter.setPreferredSize(new java.awt.Dimension(650, 398));

        pnSource.setBackground(new java.awt.Color(182, 129, 76));
        pnSource.setName("pnSource"); // NOI18N

        javax.swing.GroupLayout pnSourceLayout = new javax.swing.GroupLayout(pnSource);
        pnSource.setLayout(pnSourceLayout);
        pnSourceLayout.setHorizontalGroup(
            pnSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnSourceLayout.setVerticalGroup(
            pnSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnSplitter.setLeftComponent(pnSource);
        pnSource.getAccessibleContext().setAccessibleName("pnSrc");

        pnTarget.setBackground(new java.awt.Color(182, 129, 76));
        pnTarget.setName("pnTarget"); // NOI18N

        javax.swing.GroupLayout pnTargetLayout = new javax.swing.GroupLayout(pnTarget);
        pnTarget.setLayout(pnTargetLayout);
        pnTargetLayout.setHorizontalGroup(
            pnTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnTargetLayout.setVerticalGroup(
            pnTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnSplitter.setRightComponent(pnTarget);
        pnTarget.getAccessibleContext().setAccessibleName("pnTrg");

        getContentPane().add(pnSplitter, java.awt.BorderLayout.CENTER);
        pnSplitter.getAccessibleContext().setAccessibleName("pnSplt");

        pnToolbar.setPreferredSize(new java.awt.Dimension(125, 50));

        btnSelectImg.setText("Select Image");
        btnSelectImg.setToolTipText("Choose Image File");
        btnSelectImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectImgActionPerformed(evt);
            }
        });

        lbSelectedFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnToolbarLayout = new javax.swing.GroupLayout(pnToolbar);
        pnToolbar.setLayout(pnToolbarLayout);
        pnToolbarLayout.setHorizontalGroup(
            pnToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSelectImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSelectedFile, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addGap(180, 180, 180))
        );
        pnToolbarLayout.setVerticalGroup(
            pnToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSelectedFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnToolbarLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(btnSelectImg)
                .addContainerGap())
        );

        getContentPane().add(pnToolbar, java.awt.BorderLayout.PAGE_END);

        getAccessibleContext().setAccessibleName("uiFrame");

        setSize(new java.awt.Dimension(700, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectImgActionPerformed

        //select image file to be loaded 
        JFileChooser fileChooser = new JFileChooser();
        /* Create filter for png and jpg images only */
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG or PNG Files", "jpg", "png");
        fileChooser.setFileFilter(filter);

        int retVal = fileChooser.showOpenDialog(rootPane);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            File selected = fileChooser.getSelectedFile();
            
            //1. create JPanel with image painted
            //2. replace existing JPanel and revalidate UI.
            lbSelectedFile.setText("Selected Image: " + selected.getAbsolutePath());
            //set the bufferedImage to this panel.

            Dimension dimension = pnSource.getSize();
            ImagePanel pnCurrent = new ImagePanel(selected, dimension);
            pnSplitter.remove(pnSource);
            pnSplitter.add(pnCurrent);
            pnSplitter.revalidate();
        }
    }//GEN-LAST:event_btnSelectImgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new MainUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectImg;
    private javax.swing.JLabel lbSelectedFile;
    public javax.swing.JPanel pnSource;
    private javax.swing.JSplitPane pnSplitter;
    public javax.swing.JPanel pnTarget;
    private javax.swing.JPanel pnToolbar;
    // End of variables declaration//GEN-END:variables
}
